Changed success and cancel url in stripe
CCMKTGGP/Away pull request #25
Opened 2024-08-07 20:51 UTC by codeyumm

2024-08-12 15:54 UTC, shreynpatel23 requested changes
@codeyumm there are a lot of console.log in your code if we can remove them, that would be good, Also I have suggested some changes please take a look at that.

2024-08-12 15:54 UTC, shreynpatel23 commented on app/api/(billing)/checkout/route.ts
>        priceId = process.env.STRIPE_PRICE_ID_LIFETIME;
@codeyumm can we create constants for the mode and store then in a separate file. that is a good practice to follow. By this if we want to change it in future we know exactly where to change

2024-08-12 15:54 UTC, shreynpatel23 commented on app/api/(billing)/checkout/route.ts
> +    console.log('Metadata before sending to Stripe:', metadata);
Please remove console.log

2024-08-12 15:54 UTC, shreynpatel23 commented on app/api/webhook/route.ts
> +  if (req.method === 'POST') {
no need of this If condition as the function name is POST so next always consider this as a post request.

2024-08-12 15:54 UTC, shreynpatel23 commented
@codeyumm I think you bramch is not rebased with main branch please do that as well

2024-08-12 19:19 UTC, codeyumm commented on app/api/(billing)/checkout/route.ts
>        priceId = process.env.STRIPE_PRICE_ID_LIFETIME;
Done

2024-08-12 19:20 UTC, codeyumm commented on app/api/(billing)/checkout/route.ts
> +    console.log('Metadata before sending to Stripe:', metadata);
done

2024-08-14 15:06 UTC, shreynpatel23 approved these changes

2024-08-14 15:07 UTC, merged